site_name: Spec Portal
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - API: api.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
